// Auto-generated by Style Dictionary
export const tokens = {
  "header-xl": {"fontFamily": "Geist-Regular", "lineHeight": 44, "fontSize": 40},
  "header-lg": {"fontFamily": "Geist-Regular", "lineHeight": 36, "fontSize": 32},
  "header-md": {"fontFamily": "Geist-Regular", "lineHeight": 28, "fontSize": 24},
  "header-sm": {"fontFamily": "Geist-Regular", "lineHeight": 24, "fontSize": 20},
  "header-xs": {"fontFamily": "Geist-Medium", "fontSize": 18, "lineHeight": 20},
  "header-xxs": {"fontFamily": "Geist-Medium", "lineHeight": 18, "fontSize": 16},
  "body-lg": {"fontFamily": "Geist-Regular", "lineHeight": 24, "fontSize": 16},
  "body-lg-bold": {"fontFamily": "Geist-Medium", "lineHeight": 24, "fontSize": 16},
  "body-md": {"fontFamily": "Geist-Regular", "lineHeight": 20, "fontSize": 14},
  "body-md-bold": {"fontFamily": "Geist-Medium", "lineHeight": 20, "fontSize": 14},
  "body-sm": {"fontFamily": "Geist-Regular", "lineHeight": 16, "fontSize": 12},
  "body-sm-bold": {"fontFamily": "Geist-Medium", "lineHeight": 16, "fontSize": 12},
  "caption": {"fontFamily": "Geist-Regular", "lineHeight": 12, "fontSize": 10},
  "caption-bold": {"fontFamily": "Geist-SemiBold", "lineHeight": 12, "fontSize": 10},
  "button-lg": {"fontFamily": "Geist-Medium", "lineHeight": 16, "fontSize": 16},
  "button-sm": {"fontFamily": "Geist-Medium", "lineHeight": 14, "fontSize": 14}
};
